project:
  type: book
  output-dir: _thesis

lang: en

book:
  title: Master Thesis
  output-file: "THESIS"   # name of thesis PDF
  date: August 2023
  author:
    name: Thomas Gredig
  cover-image: https://1000logos.net/wp-content/uploads/2024/02/CSULB-Logo.png
  favicon: https://1000logos.net/wp-content/uploads/2024/02/CSULB-Logo.png
  chapters:
    - index.qmd  # required: will load 1-Introduction.qmd
    # - chapters/1-Introduction.qmd
    - chapters/2-Experiment.qmd
    - chapters/3-Results.qmd
    - chapters/4-Summary.qmd
    - references.qmd
  appendices:
    - appendix/AppendixA.qmd
  search: true
  page-footer: 
    left: |
      Copyright (c) 2025 Thomas Gredig

thesis:
  advisor: 
    name: Thomas Gredig
  committee:
    name1: Jane Doe
    name2: Jim Smith
  degree-name: M.S. Thesis
  graduation:
    date: "January 2019"
    bs:
      degree: "B.S."
      year: 1999
      university: University of Minnesota
  university: California State University Long Beach
  department: 
    name: Department of Physics and Astronomy
    chair: En Lo
  acknowledgements: "frontmatter/acknowledgements.tex"
  dedication: "frontmatter/dedication.tex"
  abstract: "frontmatter/abstract.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [references.bib]

execute:
  echo: false
  warning: false
  cache: true
  freeze: auto  # re-render only when source changes
  
format: 
  html: 
    theme: cosmo
    author-meta: "Thomas Gredig, California State University Long Beach"
  msthesis-csulb-pdf:
    output-file: pdf-book

    