project:
  type: book
  output-dir: _thesis

book:
  title: CSU Long Beach M.S. Thesis Title
  date: September 22, 2024
  author:
    name: Thomas Gredig
    url: http://www.beach77.com
  downloads: [pdf]
  abstract: "Abstract text with less than 500 words."
  chapters:
    - index.qmd   # this routes to 1-Introduction
    - chapters/1-Introduction.qmd  
    - chapters/2-Experiment.qmd
    - chapters/3-Results.qmd
    - chapters/4-Summary.qmd
    - references.qmd
  appendices:
    - appendix/AppendixA.qmd
  search: true

thesis:
  advisor: 
    name: Dr. Thomas Gredig
    url: https://home.csulb.edu/~tgredig/
  degree-name: M.S. Thesis
  university: California State University Long Beach
  department: Department of Physics and Astronomy
  acknowledgements: "frontmatter/acknowledgements.tex"
  dedication: "frontmatter/dedication.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [references.bib]

execute:
  echo: false
  warning: false
  cache: true
  freeze: auto  # re-render only when source changes

format: 
  html: default
  msthesis-csulb-pdf: default

