project:
  type: book
  output-dir: _thesis
  
lang: en

book:
  title: Master Thesis
  subtitle: Quarto Template Subtitle
  date: August 2023
  author:
    name: Thomas Gredig
  cover-image: https://1000logos.net/wp-content/uploads/2024/02/CSULB-Logo.png
  favicon: https://1000logos.net/wp-content/uploads/2024/02/CSULB-Logo.png
  chapters:
    - index.qmd  # required: will load 1-Introduction.qmd
    # - chapters/1-Introduction.qmd
    - chapters/2-Experiment.qmd
    - chapters/3-Results.qmd
    - chapters/4-Summary.qmd
    - references.qmd
  appendices:
    - appendix/AppendixA.qmd
  search: true
  page-footer: 
    left: |
      Copyright (c) 2024 Thomas Gredig

thesis:
  advisor: 
    name: Thomas Gredig
  committee:
    name1: Jane Doe
    name2: Jim Smith
  degree-name: M.S. Thesis
  graduation:
    date: "August 2023"
  university: California State University Long Beach
  department: 
    name: Department of Physics and Astronomy
    chair: Prashanth Jaikumar
  acknowledgements: "frontmatter/acknowledgements.tex"
  dedication: "frontmatter/dedication.tex"
  abstract: "frontmatter/abstract.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [references.bib]
csl: physical-review-b.csl

execute:
  echo: false
  warning: false
  cache: true
  freeze: auto  # re-render only when source changes
  
language:
  en:
    section-title-appendices: "APPENDIX"
    section-title-abstract: "ABSTRACTSSSS"
    # see https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
    
format: 
  html: 
    theme: cosmo
    css: thesis.css
    author-meta: "Thomas Gredig, California State University Long Beach"
  msthesis-csulb-pdf:
    output-file: pdf-book

    