project:
  type: book
  output-dir: _thesis

book:
  title: CSU Long Beach Masters Thesis Title
  subtitle: Quarto Template Subtitle
  date: August 2023
  author:
    name: Thomas Gredig
  downloads: [pdf]
  chapters:
    - index.qmd   # this routes to 1-Introduction
    - chapters/1-Introduction.qmd  
    - chapters/2-Experiment.qmd
    - chapters/3-Results.qmd
    - chapters/4-Summary.qmd
    - references.qmd
  appendices:
    - appendix/AppendixA.qmd
  search: true

thesis:
  advisor: 
    name: Thomas Gredig
  committee:
    name1: Jane Doe
    name2: Jim Smith
  degree-name: M.S. Thesis
  graduation:
    date: "August 2023"
  university: California State University Long Beach
  department: 
    name: Department of Physics and Astronomy
    chair: Prashanth Jaikumar
  acknowledgements: "frontmatter/acknowledgements.tex"
  dedication: "frontmatter/dedication.tex"
  abstract: "frontmatter/abstract.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [references.bib]

execute:
  echo: false
  warning: false
  cache: true
  freeze: auto  # re-render only when source changes

format: 
  html: default
  msthesis-csulb-pdf: default

